# Generated by Django 5.1.4 on 2026-09-05 09:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvisorMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("role", models.CharField(choices=[("user", "User"), ("assistant", "Assistant")], max_length=20)),
                ("content", models.TextField()),
                (
                    "topic",
                    models.CharField(
                        choices=[("MONEY", "Money"), ("TRACK_RECORD", "Track record"), ("GENERAL", "General")],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("numbers", models.JSONField(blank=True, default=list)),
                ("considerations", models.JSONField(blank=True, default=list)),
                ("watch_outs", models.JSONField(blank=True, default=list)),
                ("suggested_decision", models.JSONField(blank=True, default=dict)),
                ("provider", models.CharField(blank=True, max_length=40)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advisor_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "advisor_message",
                "ordering": ["created_at"],
            },
        ),
    ]
