# Generated by Django 5.1.4 on 2026-09-05 09:03

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("dependents", models.PositiveSmallIntegerField(default=0)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("SALARIED", "Salaried"),
                            ("SELF_EMPLOYED", "Self-employed"),
                            ("STUDENT", "Student"),
                            ("BETWEEN_JOBS", "Between jobs"),
                        ],
                        default="SALARIED",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "monthly_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "monthly_expenses",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "current_savings",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "existing_emi",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "risk_appetite",
                    models.CharField(
                        choices=[("LOW", "Cautious"), ("MEDIUM", "Balanced"), ("HIGH", "Comfortable with risk")],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("goals", models.TextField(blank=True, help_text="What they are saving or working toward.")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="profile", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "profiles_profile",
            },
        ),
    ]
