# One is shown per day, chosen by the date so it stays put for the whole day.
DAILY_QUOTES = (
    ("Whether you think you can or you think you can't, you're right.", "Henry Ford"),
    ("It does not matter how slowly you go as long as you do not stop.", "Confucius"),
    ("The best time to plant a tree was twenty years ago. The second best time is now.", "Proverb"),
    ("You miss one hundred percent of the shots you don't take.", "Wayne Gretzky"),
    ("Fall seven times, stand up eight.", "Japanese proverb"),
    ("What we think, we become.", "Buddha"),
    ("The obstacle is the way.", "Marcus Aurelius"),
    ("Do what you can, with what you have, where you are.", "Theodore Roosevelt"),
    ("A year from now you may wish you had started today.", "Karen Lamb"),
    ("Little by little, a little becomes a lot.", "Tanzanian proverb"),
    ("Start where you are. Use what you have. Do what you can.", "Arthur Ashe"),
    ("The way to get started is to quit talking and begin doing.", "Walt Disney"),
    ("It always seems impossible until it's done.", "Nelson Mandela"),
    ("Success is the sum of small efforts repeated day in and day out.", "Robert Collier"),
    ("You do not rise to the level of your goals. You fall to the level of your systems.", "James Clear"),
    ("Courage is not the absence of fear, but acting in spite of it.", "Mark Twain"),
    ("The only way out is through.", "Robert Frost"),
    ("Comparison is the thief of joy.", "Theodore Roosevelt"),
    ("Energy and persistence conquer all things.", "Benjamin Franklin"),
    ("If you want to go fast, go alone. If you want to go far, go together.", "African proverb"),
    ("Well begun is half done.", "Aristotle"),
    ("The person who moves a mountain begins by carrying away small stones.", "Confucius"),
    ("Doubt kills more dreams than failure ever will.", "Suzy Kassem"),
    ("Nothing will work unless you do.", "Maya Angelou"),
    ("Patience is bitter, but its fruit is sweet.", "Aristotle"),
    ("You are allowed to be both a masterpiece and a work in progress.", "Sophia Bush"),
    ("Discipline is choosing between what you want now and what you want most.", "Abraham Lincoln"),
    ("However difficult life may seem, there is always something you can do.", "Stephen Hawking"),
    ("Progress, not perfection.", "Anonymous"),
    ("The future depends on what you do today.", "Mahatma Gandhi"),
    ("Act as if what you do makes a difference. It does.", "William James"),
)

RECENT_NOTES_ON_HOME = 4
