# Generated by Django 5.1.4 on 2026-09-04 18:30

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Decision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=200)),
                ("context", models.TextField(help_text="Why this decision is being made, in the user's own words.")),
                ("options_considered", models.JSONField(blank=True, default=list)),
                ("chosen_option", models.CharField(max_length=300)),
                ("expected_outcome", models.TextField(help_text="What the user expects to happen if they go ahead.")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CAREER", "Career"),
                            ("MONEY", "Money"),
                            ("PRODUCT", "Product"),
                            ("HEALTH", "Health"),
                            ("RELATIONSHIP", "Relationship"),
                            ("LEARNING", "Learning"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "initial_confidence",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "final_confidence",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("review_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("LOCKED", "Locked"), ("REVIEWED", "Reviewed")],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "decisions_decision",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("READY", "Ready")], default="PENDING", max_length=20
                    ),
                ),
                ("counterarguments", models.JSONField(blank=True, default=list)),
                ("blind_spots", models.JSONField(blank=True, default=list)),
                ("failure_conditions", models.JSONField(blank=True, default=list)),
                ("sharpest_question", models.TextField(blank=True)),
                ("provider", models.CharField(blank=True, max_length=40)),
                (
                    "decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="challenge", to="decisions.decision"
                    ),
                ),
            ],
            options={
                "db_table": "decisions_challenge",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("kind", models.CharField(choices=[("REVIEW_DUE", "Review due")], max_length=30)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="decisions.decision",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "decisions_notification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[("RIGHT", "Right"), ("WRONG", "Wrong"), ("MIXED", "Mixed")], max_length=10
                    ),
                ),
                ("what_happened", models.TextField()),
                ("lesson", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="review", to="decisions.decision"
                    ),
                ),
            ],
            options={
                "db_table": "decisions_review",
            },
        ),
        migrations.AddIndex(
            model_name="decision",
            index=models.Index(fields=["user", "status", "review_date"], name="decisions_d_user_id_5e70fb_idx"),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("user", "decision", "kind"), name="uniq_notification_per_decision_kind"
            ),
        ),
    ]
