# Generated by Django 5.1.4 on 2026-09-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insights", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatMessage",
        ),
    ]
