import { useCallback, useEffect, useRef, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { api } from "../api";
import { Badge, Button, Card, ConfidenceSlider, Field, Loading, Select, Textarea } from "../components/ui";

const OUTCOME_LABELS = {
  RIGHT: "I was right",
  MIXED: "Partly right",
  WRONG: "I was wrong",
};

export default function DecisionDetail() {
  const { uuid } = useParams();
  const navigate = useNavigate();
  const [decision, setDecision] = useState(null);
  const [error, setError] = useState(null);
  const pollRef = useRef(null);

  const load = useCallback(() => api(`/decisions/${uuid}/`).then(setDecision), [uuid]);

  useEffect(() => {
    load().catch((caught) => setError(caught.message));
  }, [load]);

  // The challenge is generated by a Celery worker, so poll until it lands.
  useEffect(() => {
    if (decision?.challenge?.status !== "PENDING") {
      clearInterval(pollRef.current);
      return;
    }
    pollRef.current = setInterval(() => load().catch(() => {}), 1500);
    return () => clearInterval(pollRef.current);
  }, [decision?.challenge?.status, load]);

  if (error) return <p className="py-16 text-center text-sm text-bad">{error}</p>;
  if (!decision) return <Loading />;

  const { challenge, review, status } = decision;

  return (
    <div className="mx-auto max-w-2xl space-y-6">
      <div>
        <div className="flex flex-wrap items-center gap-2">
          <Badge tone={review?.outcome || status}>{review?.outcome || status}</Badge>
          <span className="text-[11px] uppercase tracking-wider text-mute">{decision.category}</span>
        </div>
        <h1 className="serif mt-3 text-2xl leading-snug text-paper">{decision.title}</h1>
      </div>

      <Card className="divide-y divide-line">
        <Detail label="Why">{decision.context}</Detail>
        {decision.options_considered.length > 0 && (
          <Detail label="Options weighed">
            <ul className="space-y-1">
              {decision.options_considered.map((option) => (
                <li key={option} className={option === decision.chosen_option ? "text-paper" : "text-mute"}>
                  {option === decision.chosen_option ? "→ " : "· "}
                  {option}
                </li>
              ))}
            </ul>
          </Detail>
        )}
        <Detail label="Going with">{decision.chosen_option}</Detail>
        <Detail label="Expecting">{decision.expected_outcome}</Detail>
        <div className="flex items-center gap-8 p-5">
          <div>
            <p className="text-[11px] font-medium uppercase tracking-wider text-mute">Confidence</p>
            <p className="mt-1 text-2xl font-semibold tabular-nums text-accent">{decision.scored_confidence}%</p>
          </div>
          {decision.confidence_shift !== null && decision.confidence_shift !== 0 && (
            <div>
              <p className="text-[11px] font-medium uppercase tracking-wider text-mute">Moved by the challenge</p>
              <p className="mt-1 text-2xl font-semibold tabular-nums text-soft">
                {decision.confidence_shift > 0 ? "+" : ""}
                {decision.confidence_shift}
                <span className="ml-1 text-sm text-mute">from {decision.initial_confidence}%</span>
              </p>
            </div>
          )}
          <div className="ml-auto text-right">
            <p className="text-[11px] font-medium uppercase tracking-wider text-mute">Review date</p>
            <p className="mt-1 text-sm text-soft">{decision.review_date}</p>
          </div>
        </div>
      </Card>

      {status === "DRAFT" && !challenge && <ChallengePrompt uuid={uuid} onStarted={load} />}
      {challenge?.status === "PENDING" && (
        <Card className="p-6 text-center text-sm text-mute">
          Building the case against you… <span className="text-accent">this runs in the background</span>
        </Card>
      )}
      {challenge?.status === "READY" && <ChallengePanel challenge={challenge} />}

      {status === "DRAFT" && challenge?.status === "READY" && (
        <ReviseAndLock decision={decision} onDone={load} />
      )}
      {status === "DRAFT" && !challenge && <LockOnly uuid={uuid} onDone={load} />}

      {status === "LOCKED" && <ReviewForm uuid={uuid} onDone={load} />}
      {review && <ReviewPanel review={review} />}

      <button onClick={() => navigate("/")} className="text-sm text-mute transition hover:text-soft">
        ← Back to all decisions
      </button>
    </div>
  );
}

function Detail({ label, children }) {
  return (
    <div className="p-5">
      <p className="text-[11px] font-medium uppercase tracking-wider text-mute">{label}</p>
      <div className="mt-1.5 whitespace-pre-wrap text-sm leading-relaxed text-soft">{children}</div>
    </div>
  );
}

function ChallengePrompt({ uuid, onStarted }) {
  const [busy, setBusy] = useState(false);

  async function start() {
    setBusy(true);
    await api(`/decisions/${uuid}/challenge/`, { method: "POST" });
    await onStarted();
  }

  return (
    <Card className="p-6">
      <p className="serif text-lg text-paper">Before you commit, hear the other side.</p>
      <p className="mt-2 text-sm text-mute">
        The AI will argue against this decision using your own reasoning — the counterarguments, the assumptions
        you are treating as facts, and the specific ways this fails. You get one chance to revise your confidence
        afterwards.
      </p>
      <Button onClick={start} disabled={busy} className="mt-4">
        {busy ? "Starting…" : "Argue against me"}
      </Button>
    </Card>
  );
}

function ChallengePanel({ challenge }) {
  const sections = [
    { title: "The case against", items: challenge.counterarguments },
    { title: "What you are not seeing", items: challenge.blind_spots },
    { title: "How this fails", items: challenge.failure_conditions },
  ];

  return (
    <Card className="overflow-hidden">
      <div className="flex items-center justify-between border-b border-line bg-raised px-5 py-3">
        <p className="text-sm font-medium text-paper">Devil's advocate</p>
        <span className="text-[11px] uppercase tracking-wider text-mute">via {challenge.provider}</span>
      </div>
      <div className="divide-y divide-line">
        {sections.map((section) => (
          <div key={section.title} className="p-5">
            <p className="text-[11px] font-medium uppercase tracking-wider text-mute">{section.title}</p>
            <ul className="mt-2.5 space-y-2">
              {section.items.map((item, index) => (
                <li key={index} className="flex gap-2.5 text-sm leading-relaxed text-soft">
                  <span className="text-accent">—</span>
                  {item}
                </li>
              ))}
            </ul>
          </div>
        ))}
        <div className="bg-accent/[0.06] p-5">
          <p className="text-[11px] font-medium uppercase tracking-wider text-mute">The question to sit with</p>
          <p className="serif mt-2 text-lg leading-snug text-paper">{challenge.sharpest_question}</p>
        </div>
      </div>
    </Card>
  );
}

function ReviseAndLock({ decision, onDone }) {
  const [confidence, setConfidence] = useState(decision.scored_confidence);
  const [busy, setBusy] = useState(false);

  async function lockIt() {
    setBusy(true);
    if (confidence !== decision.scored_confidence) {
      await api(`/decisions/${decision.uuid}/confidence/`, {
        method: "PATCH",
        body: { final_confidence: confidence },
      });
    }
    await api(`/decisions/${decision.uuid}/lock/`, { method: "POST" });
    await onDone();
  }

  const shift = confidence - decision.initial_confidence;

  return (
    <Card className="p-6">
      <p className="text-xs font-medium uppercase tracking-wider text-mute">Still as confident?</p>
      <div className="mt-4">
        <ConfidenceSlider value={confidence} onChange={setConfidence} />
      </div>
      {shift !== 0 && (
        <p className="mt-3 text-sm text-soft">
          That is {Math.abs(shift)} points {shift < 0 ? "lower" : "higher"} than where you started. Both numbers
          are kept.
        </p>
      )}
      <div className="mt-6 border-t border-line pt-5">
        <p className="text-sm text-mute">
          Locking freezes this record permanently. You will not be able to edit your reasoning after you know how
          it turned out — which is the entire point.
        </p>
        <Button onClick={lockIt} disabled={busy} className="mt-4">
          {busy ? "Locking…" : "Lock this decision"}
        </Button>
      </div>
    </Card>
  );
}

function LockOnly({ uuid, onDone }) {
  const [busy, setBusy] = useState(false);

  async function lockIt() {
    setBusy(true);
    await api(`/decisions/${uuid}/lock/`, { method: "POST" });
    await onDone();
  }

  return (
    <Card className="p-6">
      <p className="text-sm text-mute">
        You can lock this without being challenged, but you will lose the most interesting number in the app —
        how much a good argument moves you.
      </p>
      <Button variant="ghost" onClick={lockIt} disabled={busy} className="mt-4">
        {busy ? "Locking…" : "Lock without a challenge"}
      </Button>
    </Card>
  );
}

function ReviewForm({ uuid, onDone }) {
  const [form, setForm] = useState({ outcome: "RIGHT", what_happened: "", lesson: "" });
  const [busy, setBusy] = useState(false);
  const update = (key) => (event) => setForm({ ...form, [key]: event.target.value });

  async function submit(event) {
    event.preventDefault();
    setBusy(true);
    await api(`/decisions/${uuid}/review/`, { method: "POST", body: form });
    await onDone();
  }

  return (
    <Card className="p-6">
      <p className="serif text-lg text-paper">So — what actually happened?</p>
      <form onSubmit={submit} className="mt-4 space-y-4">
        <Field label="Outcome">
          <Select value={form.outcome} onChange={update("outcome")}>
            {Object.entries(OUTCOME_LABELS).map(([value, label]) => (
              <option key={value} value={value}>
                {label}
              </option>
            ))}
          </Select>
        </Field>
        <Field label="What happened" hint="Including the part that surprised you.">
          <Textarea required rows={4} value={form.what_happened} onChange={update("what_happened")} />
        </Field>
        <Field label="What you would tell yourself">
          <Textarea rows={2} value={form.lesson} onChange={update("lesson")} placeholder="Optional" />
        </Field>
        <Button type="submit" disabled={busy}>
          {busy ? "Saving…" : "Score this decision"}
        </Button>
      </form>
    </Card>
  );
}

function ReviewPanel({ review }) {
  return (
    <Card className="overflow-hidden">
      <div className="flex items-center justify-between border-b border-line bg-raised px-5 py-3">
        <p className="text-sm font-medium text-paper">What happened</p>
        <Badge tone={review.outcome}>{OUTCOME_LABELS[review.outcome]}</Badge>
      </div>
      <div className="divide-y divide-line">
        <Detail label="Outcome">{review.what_happened}</Detail>
        {review.lesson && <Detail label="The lesson">{review.lesson}</Detail>}
      </div>
    </Card>
  );
}
