CATEGORY_CAREER = "CAREER"
CATEGORY_MONEY = "MONEY"
CATEGORY_PRODUCT = "PRODUCT"
CATEGORY_HEALTH = "HEALTH"
CATEGORY_RELATIONSHIP = "RELATIONSHIP"
CATEGORY_LEARNING = "LEARNING"
CATEGORY_OTHER = "OTHER"

CATEGORY_CHOICES = (
    (CATEGORY_CAREER, "Career"),
    (CATEGORY_MONEY, "Money"),
    (CATEGORY_PRODUCT, "Product"),
    (CATEGORY_HEALTH, "Health"),
    (CATEGORY_RELATIONSHIP, "Relationship"),
    (CATEGORY_LEARNING, "Learning"),
    (CATEGORY_OTHER, "Other"),
)

STATUS_DRAFT = "DRAFT"
STATUS_LOCKED = "LOCKED"
STATUS_REVIEWED = "REVIEWED"

STATUS_CHOICES = (
    (STATUS_DRAFT, "Draft"),
    (STATUS_LOCKED, "Locked"),
    (STATUS_REVIEWED, "Reviewed"),
)

CHALLENGE_PENDING = "PENDING"
CHALLENGE_READY = "READY"

CHALLENGE_STATUS_CHOICES = (
    (CHALLENGE_PENDING, "Pending"),
    (CHALLENGE_READY, "Ready"),
)

OUTCOME_RIGHT = "RIGHT"
OUTCOME_WRONG = "WRONG"
OUTCOME_MIXED = "MIXED"

OUTCOME_CHOICES = (
    (OUTCOME_RIGHT, "Right"),
    (OUTCOME_WRONG, "Wrong"),
    (OUTCOME_MIXED, "Mixed"),
)

# How much of a "right" a mixed outcome is worth when scoring calibration.
OUTCOME_SCORES = {
    OUTCOME_RIGHT: 1.0,
    OUTCOME_MIXED: 0.5,
    OUTCOME_WRONG: 0.0,
}

NOTIFICATION_REVIEW_DUE = "REVIEW_DUE"
NOTIFICATION_KIND_CHOICES = ((NOTIFICATION_REVIEW_DUE, "Review due"),)

CONFIDENCE_BUCKETS = ((0, 20), (20, 40), (40, 60), (60, 80), (80, 101))
MIN_REVIEWS_FOR_INSIGHTS = 3
DEFAULT_PAGE_SIZE = 20
